viewer:
  Title : "Go语言博客"
  Description : "Go语言博客"
  Logo : "/resource/images/logo.png"
  Navigation : ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
  Bilibili : "xxx"
  Zhihu : "xxx"
  Avatar : "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Finews.gtimg.com%2Fnewsapp_bt%2F0%2F13147603927%2F1000.jpg&refer=http%3A%2F%2Finews.gtimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1647242040&t=c6108010ed46b4acebe18955acdd2d24"
  UserName : "haha"
  UserDesc : "长得非常帅的程序员"


system:
  CdnURL : "https://static.mszlu.com/goblog/es6/md-assets"
  QiniuAccessKey : "XG-y4RatbGeHaYcDm474uVBYyfDG5f2pgIx8qZUl"
  QiniuSecretKey : "GFhMucX29If5Rs5xEqICj1Tv-mc5EnPNxO8crQJH"
  Valine : true
  ValineAppid : "TWojjl4R6DV3eEaiAfb16PTv-gzGzoHsz"
  ValineAppkey : "AB1nyR9IBUntAMr7FLlc3BdN"
  ValineServerURL : "https://twojjl4r.lc-cn-n1-shared.com"


# mysql connect configuration
# 未初始化之前请勿手动修改数据库信息！！！如果一定要手动初始化请看（https://gin-vue-admin.com/docs/first_master）
mysql:
  path: "localhost"
  port: "3306"
  config: "charset=utf8&loc=%s&parseTime=true"
  db-name: "goblog"
  username: "root"
  password: "root"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false


# redis configuration
redis:
  #是否使用redis集群模式
  useCluster: false
  #使用集群模式addr和db默认无效
  addr: 127.0.0.1:6379
  password: ""
  db: 0
  clusterAddrs:
    - "172.21.0.3:7000"
    - "172.21.0.4:7001"
    - "172.21.0.2:7002"

output: ""